### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [LilJohny/Text_Summarizer#1]
1. Погано не думати, а робити по шаблону
Проблеми:

    Яким чином розпізнати та розібрати 34 шематизми, які збережені у форматах pdf або djvu.
    Структура описів населених пунктів в різні роки різна.
    Мова в шематизмах різна.

2. FastText це більш точна модель
3. Генерувати заголовки погана ідея бо якраз їх якість має бути високою щоб на новину звернули увагу
4. Василь Старко - один з розробників корпусу української мови викладач нашої кафедри.
5. Бракує чіткості у формулюванні завдань. Їх занадто багато перелічено.
6. За описом зрозумів що це extractive text summarization
7. Перед тим як далі щось робити знайдіть табличку з порівнянням якості різних алгоритмів text summarization.
8. https://github.com/Kyubyong/nlp_tasks
9. http://textsummarization.net/text-summarization-api-for-python

Тема: Дослідження алгоритмів автоматичного реферування текстів природною мовою. 
Затверджено: 04.03.2019

**Comment by TroublingStone** [comment]
@anrom7  Ці проблеми з'явилися випадково, я намагався відобразити зміст і не міг зрозуміти чому у вашому файлі він є, а в моєму, майже ідентичному немає. Вибачаюся за це, виправлю, але друга ревізія фалу з тижневими звітами містить доречні проблеми.
